header:
    title: Welcome to our Data Lab
    text: It's Nice To Meet You
    button: Tell Me More
    buttonlink: "#services"

services:
    title: "Services"
    text: "Our Services"
    section: services
    list:
      - title: "Data Scraping"
        desc: "We provide scripts to scrape different websites using python tools like bs4, selenium, scrappy."
        icon: fas fa-shopping-cart #find more at https://fontawesome.com/icons
      - title: "Python Automation"
        desc: "Your boring tasks can be automated by our scaleable scripts."
        icon: fas fa-laptop       
      - title: "Bio Informatics"
        desc: "We solve bio informatics related problem."
        icon: fas fa-biohazard

portfolio:
    title: "Portfolio"
    text: "Our Projects."
    section: portfolio
    closebutton: "Close Project"
    

timeline:
    title: "About" 
    text: "Our Timeline"
    section: timeline
    events:
      - title: "Our Humble Beginnings"
        year: "2018"
        desc: "Like minded individual passionate about data, science and tech to form a unique team."
        image: assets/img/timeline/1.jpg
        alt: 
        align: left
      # - title: "An Agency is Born"
      #   year: "March 2011"
      #   desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
      #   image: assets/img/timeline/2.jpg
      #   alt: 
      #   align: right
      - title: "First project Completed"
        year: "2019"
        desc: "We collectively made vcfparser python package."
        image: assets/img/timeline/3.jpg
        alt: image alt text
        align: right
        #default is left       
      - title: "Working for clients"
        year: "2020"
        desc: "After 2 years of building internal tools we started doing freelancing projects."
        image: assets/img/timeline/4.jpg
        alt: 
        align: left
    end: "Be Part <br> of Our <br> Story!"

about:
    title: "About Us"
    text: "our story"
    section: about

clients:
    section: clients
    max-height: 100px
    horizontal-scrolling: "yes" #"yes/no"
    list:
      - title: "Kely Dang"
        url: https://github.com/raviriley/agency-jekyll-theme
        logo: assets/img/clients/envato.jpg
      - title: "Vikent"
        url: https://github.com/raviriley/agency-jekyll-theme
        logo: assets/img/clients/designmodo.jpg
      - title: "themeforest"
        url: https://github.com/raviriley/agency-jekyll-theme
        logo: assets/img/clients/themeforest.jpg
      - title: "Creative Market"
        url: https://github.com/raviriley/agency-jekyll-theme
        logo: assets/img/clients/creative-market.jpg
    
team:
    title: "OUR AMAZING TEAM"
    text: "We are weavers."
    subtext: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde. **Markdown** supported.
    section: team
    people:
      - name: "Bishwa K Giri"
        role: "CEO/ Project Manager"
        image: assets/img/team/kiran.jpeg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "Bhuwan Aryal"
        role: "Lead Developer"
        image: assets/img/team/vuon.JPG
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "Gopal Kisi"
        role: "Lead Developer"
        image: assets/img/team/gopal.jpeg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
          
contact:
    title: "Contact Us"
    text: "Call us at 9860401886"
    section: contact
    
footer:
    legal: "Privacy Policy"
    social:
      - url: https://twitter.com
        icon: "fab fa-twitter"  
      - url: https://facebook.com
        icon: "fab fa-facebook-f"
      - url: https://linkedin.com
        icon: "fab fa-linkedin-in"
      - url: https://github.com/raviriley/agency-jekyll-theme
        icon: "fab fa-github"
      - url: https://instagram.com
        icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}